# Generated by Django 5.1.2 on 2025-06-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
    ]
