# Generated by Django 5.1.2 on 2025-05-21 14:43

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
